# Generated by Django 3.1.4 on 2020-12-13 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paste', '0003_pastebox_paste_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pastebox',
            old_name='paste_box',
            new_name='paste',
        ),
    ]
