# Generated by Django 3.1.4 on 2020-12-13 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paste', '0004_auto_20201213_0027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pastebox',
            name='pub_date',
        ),
    ]
