# Generated by Django 3.1.4 on 2020-12-13 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paste', '0005_remove_pastebox_pub_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pastebox',
            old_name='paste_title',
            new_name='title',
        ),
    ]
